version: '3.5'
services:
    carritocompraReact:
        image: node:14-alpine
        working_dir: /app
        command: npm start
        ports:
         - "3000:3000"
        volumes:
         - ./:/app/